### ISSUE TITLE
github actions: error while loading shared libraries: libicuuc.so

### ISSUE THREAD

**Issue by ryandotsmith** [theseus-rs/postgresql-embedded#56]
Hi. Great crate! Really appreciate it.

I'm having an issue running on github actions. Works fine on my mac. And on my personal linux server.

I noticed that you are testing on GH actions. Was there anything special you had to do in order for things to work?

```
name: test
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-features
```
```
% cat Cargo.toml| grep postgresql
    postgresql_embedded = "0.8"
```
```rust
  let mut db = PostgreSQL::new("16.2.0".parse().unwrap(), Settings::default());
```
```
setting up pg: DatabaseInitializationError(Command error: stdout=; stderr=/tmp/pg/16.2.0/bin/initdb: error while loading shared libraries: libicuuc.so.72: cannot open shared object file: No such file or directory
```
